Update apache-sshd.md
fingolfin/ssh-comparison pull request #74
Opened 2020-04-21 18:40 UTC by FliegenKLATSCH

2020-04-28 21:26 UTC, fingolfin requested changes
Thank you! However, I have some concerns about this PR.

2020-04-28 21:26 UTC, fingolfin commented on _impls/apache-sshd.md
> +        - aes128ctr
That's wrong, I am afraid. These strings must match *exactly* what the RFC mandates.

See also https://github.com/apache/mina-sshd/blob/808cdeaccaeb9e42670c06cae175dafa0e9ce21a/sshd-common/src/main/java/org/apache/sshd/common/cipher/BuiltinCiphers.java#L320-L329

2020-04-28 21:26 UTC, fingolfin commented on _impls/apache-sshd.md
> +        - ssh-rsa
Please don't reorder without need, that just makes the diff bigger. I mean, I would understand if you e.g. sorted everything alphabetically (but if you feel tempted to do so, *please* do it in a separate commit); but this seems just random, as `ssh-rsa` now is followed by `rsa-sha2` etc.

2020-04-28 21:26 UTC, fingolfin commented on _impls/apache-sshd.md
> +        - nistp521
These are not valid hostkey formats.

2020-04-28 21:26 UTC, fingolfin commented on _impls/apache-sshd.md
> -        - ecdsa-sha2-nistp521
Are you sure those were removed? There are still tests for them in the mina-sshd repository

2020-04-28 21:26 UTC, fingolfin commented on _impls/apache-sshd.md
> -        - diffie-hellman-group-exchange-sha1
contradicts https://github.com/apache/mina-sshd/blob/0da9e23c693323fe1d4f42ee702f0c2d8a1bd534/sshd-core/src/main/java/org/apache/sshd/common/kex/BuiltinDHFactories.java#L400

2020-04-28 21:26 UTC, fingolfin commented on _impls/apache-sshd.md
> +        - hmacsha1
These are not valid MAC names

2020-04-28 21:26 UTC, fingolfin commented on _impls/apache-sshd.md
> -        - hmac-sha2-512             # was brokeb before 1.1.0
Why was the comment removed?

2020-05-02 18:05 UTC, FliegenKLATSCH commented
I just copy pasted from their readme, was apparently not the best idea :$

2020-05-03 09:13 UTC, fingolfin approved these changes

2020-05-03 09:13 UTC, merged